version: '2.1'

services:
  credit_card_accounts_service:
    build:
      context: .
    image: open-banking/credit-card-accounts:0.0.1-SNAPSHOT
    container_name: card-service
    ports:
      - "8082:8082"
    depends_on:
      mysql_service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/credit_card_accounts_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend

  mysql_service:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=credit_card_accounts_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - backend

networks:
  backend:
    driver: bridge