server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/credit_card_accounts_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  sql:
    init:
      mode: always
